modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/dragon-forge/ZeithTech/issues"
license = "All rights reserved"
[[mods]]
modId = "zeithtech"
version = "${file.jarVersion}"
displayName = "ZeithTech"
updateJSONURL = "http://dccg.herokuapp.com/api/fmluc/<CFID>"
displayURL = "http://dccg.herokuapp.com/api/fmlhp/<CFID>"
logoFile = "zeithtech.png" #optional
credits = "None" #optional
authors = "Zeitheron" #optional
description = '''
Tech mod for modern Minecraft, developed by Zeitheron.
'''
[[dependencies.zeithtech]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"
[[dependencies.zeithtech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.zeithtech]]
modId = "hammerlib"
mandatory = true
versionRange = "[19.1,)"
ordering = "NONE"
side = "BOTH"
