modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/dragon-forge/ZeithTech/issues"
license = "All rights reserved"

[[mods]]
modId = "zeithtech"
version = "${file.jarVersion}"
displayName = "ZeithTech"
updateJSONURL = "http://h.zeith.org/api/fmluc/684539"
displayURL = "https://tech.zeith.org/"
logoFile = "zeithtech.png"
credits = "Zeitheron, Yukensha, Borindeus"
authors = "Zeitheron"

description = '''
Tech mod for modern Minecraft versions. Brings a lot of tiered technology into the game. Inspired by classic Industrial Craft 2, Buildcraft and a few other mods, while also bringing a lot of new and unique mechanics, blocks and complex machinery to automate your world.
'''

[[dependencies.zeithtech]]
modId = "forge"
mandatory = true
versionRange = "[43.1.43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zeithtech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zeithtech]]
modId = "hammerlib"
mandatory = true
versionRange = "[19.2.37,)"
ordering = "NONE"
side = "BOTH"
